<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data Pengguna</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #333; }
        h2 { text-align: center; color: #4f46e5; margin-bottom: 4px; }
        p.subtitle { text-align: center; color: #888; margin-top: 0; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #4f46e5; color: #fff; padding: 8px 10px; text-align: left; }
        td { padding: 7px 10px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) td { background: #f9fafb; }
        .badge-active { color: #16a34a; font-weight: bold; }
        .badge-inactive { color: #dc2626; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #aaa; }
    </style>
</head>
<body>
    <h2>📋 Data Pengguna</h2>
    <p class="subtitle">StarterPack &mdash; Dicetak: {{ date('d/m/Y H:i') }} &mdash; Total: {{ count($users) }} pengguna</p>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Tanggal Dibuat</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $i => $user)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->roles->pluck('name')->implode(', ') ?: '-' }}</td>
                <td class="{{ $user->status === 'active' ? 'badge-active' : 'badge-inactive' }}">
                    {{ $user->status === 'active' ? 'Aktif' : 'Nonaktif' }}
                </td>
                <td>{{ $user->created_at->format('d/m/Y') }}</td>
            </tr>
            @empty
            <tr><td colspan="6" style="text-align:center">Tidak ada data</td></tr>
            @endforelse
        </tbody>
    </table>
    <p class="footer">Generated by StarterPack &bull; React + Laravel</p>
</body>
</html>
